1_web_app_technologies_and_django/first_django_app/go_back_start_again/go_back_start_again/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include


urlpatterns = [
    path('polls/', include('polls.urls')),
    path('gview/', include('gview.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
]

1_web_app_technologies_and_django/first_django_app/go_back_start_again/gview/urls.py
from django.urls import path
from django.views.generic.base import TemplateView
from .views import ListApple
from .views import CsrfProtectedForm
from .views import ProtectedView


app_name='gview'


urlpatterns = [
    # Wired an index or anything view into the URLconf
    path(
        '', 
        TemplateView.as_view(template_name="gview/index.html"), 
        name="gview-index"
    ),
    path('apples', ListApple.as_view(), name='apple-list'),
    path('guess', CsrfProtectedForm.as_view(), name='guess-me-protected'),
    path('protected-route', ProtectedView.as_view(), name='protected-route'),
]

1_web_app_technologies_and_django/first_django_app/go_back_start_again/polls/urls.py
from django.urls import path
from .views import index
from .views import GameView


app_name='polls'


urlpatterns = [
    # Wired an index or anything view into the URLconf
    path('', index, name='index'),
    path('game/<int:guess>', GameView.as_view())
]

1_web_app_technologies_and_django/first_django_app/go_back_start_again/gview/models.py
from django.db import models


# Create your models here.
class Apple(models.Model):
    color: str = models.CharField(max_length=6)
    pub_date = models.DateTimeField()

1_web_app_technologies_and_django/first_django_app/go_back_start_again/polls/models.py
from django.db import models

# Create your models here.

1_web_app_technologies_and_django/first_django_app/go_back_start_again/gview/views.py
from django.views.generic import ListView
from django.views.generic import View
from django.http import HttpRequest
from django.http import HttpResponse
from django.shortcuts import redirect
from django.shortcuts import reverse
from django.shortcuts import render 
from django.contrib.auth.mixins import LoginRequiredMixin
# from datetime import datetime
from django.utils import timezone
from .models import Apple


# Create your views here.
class ListApple(ListView):
    model = Apple
    paginate_by = 100  # if pagination is desired

    # This name is preserved
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['now'] = timezone.now()
        # context['now'] = datetime.now()
        """
        - datetime.now()
        I guess we do not like this one too much
        Returns local time: datetime.datetime(2022, 7, 3, 18, 40, 31, 441670)
        - timezone.now()
        Read USE_TZ and generate time based on this setting
        """
        return context


class CsrfProtectedForm(View):
    # This "get" specify the HTTP verb
    # def get(self, req: HttpRequest):
    #     return render(req, 'gview/csrf_protected_form.html')
    
    # def get(self, req: HttpRequest):
    #     # <flash-message>
    #     guessed_number = req.session.get('guessed_number', False)
    #     if guessed_number != False:
    #         del(req.session['guessed_number'])
    #     context = {"guessed_number": guessed_number}
    #     # </flash-message>

    #     return render(req, 'gview/csrf_protected_form.html', context)

    def get(self, req: HttpRequest):
        # <flash-message>
        guessed_number = req.session.get('guessed_number', False)
        if guessed_number != False:
            del(req.session['guessed_number'])
        context = {
            "guessed_number": guessed_number,
            "logout": reverse('logout'),
            "login": reverse('login'),
        }
        # </flash-message>

        return render(req, 'gview/csrf_protected_form.html', context)
    
    # This "post" specify the HTTP verb
    # def post(self, req: HttpRequest):
    #     guess = req.POST.get('guess')
    #     context = {"guess": guess}
    #     return render(req, 'gview/csrf_protected_form.html', context)

    def post(self, req: HttpRequest):
        guess = req.POST.get('guess')
        req.session['guessed_number'] = guess
        return redirect(req.path)


class ProtectedView(LoginRequiredMixin, View):
    login_url = 'login'
    # No effect. IDK how I should configure it. I do not care too much about it right now
    # redirect_field_name = 'redirect_to'
    
    def get(self, req: HttpRequest) -> HttpResponse:
        return HttpResponse('I am protected')

1_web_app_technologies_and_django/first_django_app/go_back_start_again/polls/views.py
from django.http.request import HttpRequest
from django.http import HttpResponse
from django.views import View
from django.shortcuts import render


def index(req: HttpRequest) -> HttpResponse:
    return HttpResponse(
        "Hello, world. You're at the polls index."
    )
    
class GameView(View):
    # This "get" specify the HTTP verb
    def get(self, req: HttpRequest, guess: int) -> HttpResponse:
        data = { "user_guess": guess }
        return render(req, 'polls/user_guess.html', data)

1_web_app_technologies_and_django/first_django_app/go_back_start_again/gview/templates/gview/apple_list.html
<h1>Apples</h1>
<ul>
  {% for apple in object_list %}
  <li>{{ apple.pub_date|date }} - {{ apple.color }}</li>
  {% empty %}
  <li>No apples yet.</li>
  {% endfor %}
</ul>

1_web_app_technologies_and_django/first_django_app/go_back_start_again/gview/templates/gview/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block menu %}{% endblock %}
    <br />
    {% block csrf_protected_form %}{% endblock %}
    <br />
  </body>
</html>

1_web_app_technologies_and_django/first_django_app/go_back_start_again/gview/templates/gview/csrf_protected_form.html
{% extends "gview/base.html" %}
<br />
{% block menu %}
<ul>
  {% if user.is_authenticated %}
  <li>
    <!-- <a href="{{login}}">Login</a> -->
    <a href="{% url 'login' %} ?next= {{ request.path }}">Login</a>
  </li>
  {% else %}
  <li>
    <!-- <a href="{{logout}}">Logout</a> -->
    <a href="{% url 'logout' %} ?next= {% url 'authz:open' %}">Logout</a>
  </li>
  {% endif %}
</ul>
{% endblock %}
<br />
{% block csrf_protected_form %}
<p>CSRF protected form ...</p>
<form method="post">
  <p>
    <label for="guess"> Guess: </label>
    <input type="text" name="guess" id="guess" />
  </p>
  <input type="submit" value="I did my choice!" />
  {% csrf_token %}
</form>
{% if guessed_number %}
<div>You entered {{guessed_number}}</div>
{% endif %}
<br />
{% endblock %}

1_web_app_technologies_and_django/first_django_app/go_back_start_again/gview/templates/gview/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <!-- 
      Hard coded url
      No flexibility
     -->
    <a href="/polls/game/73">Click me to go back to game</a>
  </body>
</html>

1_web_app_technologies_and_django/first_django_app/go_back_start_again/polls/templates/polls/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    {% block content %}{% endblock %}
  </body>
</html>

1_web_app_technologies_and_django/first_django_app/go_back_start_again/polls/templates/polls/user_guess.html
{% extends "polls/base.html" %} {% block content %}
<div>{{ user_guess }}</div>
<!-- Dynamic routing -->
<a href="{% url 'gview:gview-index' %}">Just a dynamic routing link</a>
{% endblock %}

1_web_app_technologies_and_django/first_django_app/go_back_start_again/templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <ul class="sidebar-nav">
      {% if user.is_authenticated %}
      <li>User: {{ user.get_username }}</li>
      <li><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
      {% else %}
      <li><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
      {% endif %}
    </ul>

    {% block content %}{% endblock %}
  </body>
</html>